services:
  db:
    image: postgres:${PG_VERSION}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
    ports:
      - ${PG_PORT}
  web:
    build:
      context: .
      dockerfile: Containerfile
    command: uv run web-apps/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: db
      PG_PORT: ${PG_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  postgres_data:
