services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${pg_name} 
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_password} 
    ports:
      - "5432"
  web:
    build:
      context: .
      dockerfile: Containerfile
    command: uv run web-apps/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ${pg_name}
      DB_USER: ${pg_user}
      DB_PASSWORD: ${pg_password}
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  postgres_data:
