dbt_chatbots:
  target: dev
  outputs:
    dev:
      dbname: "{{ env_var('PG_USER') }}"
      user: "{{ env_var('PG_USER') }}"
      host: "{{ env_var('PG_HOST') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 2
      type: postgres
