---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: twinbots-app
spec:
  selector:
    app: twinbots-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: twinbots-app
spec:
  type: ClusterIP
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
