name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Source env variables
        run: echo "Hello"
      - name: Source env variables
        run: echo "${{pg_port}}"
      - name: Source env variables
        run: echo "${{PG_PORT}}"
      - name: Build container images
        run: docker compose build
      - name: Build container images
        run: docker ps

      # - name: tag docekr image to ACR
      #   uses: docker tag twinbots-web acrtwinbots.azurecr.io/twinbots-web:latest

