name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: source env variables
        uses: source .envrc

      - name: build docker image
        uses: docker copose build

      # - name: tag docekr image to ACR
      #   uses: docker tag twinbots-web acrtwinbots.azurecr.io/twinbots-web:latest

